server {
    listen 80 default_server;

    location = /privacy {
        root /usr/share/nginx/html;
        try_files /privacy.html =404;
        add_header Cache-Control "no-store";
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}